import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {FileStore}=require('../electron/files.cjs');
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cmd-send-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return {dir,store:new FileStore()};}
test('BOM, CRLF, Chinese and emoji survive atomic save',async t=>{const {dir,store}=await fixture(t),p=path.join(dir,'a.txt');await fs.writeFile(p,'\uFEFF[A]\r\n你好😀\r\n');const f=await store.open(p);assert.equal(f.text,'[A]\n你好😀\n');assert.equal(f.bom,true);assert.equal(f.newline,'CRLF');await store.save(f.id,'[B]\n甲😀\n');assert.equal(await fs.readFile(p,'utf8'),'\uFEFF[B]\r\n甲😀\r\n');assert.deepEqual(await fs.readdir(dir),['a.txt']);});
test('same real path reuses ID without replacing a buffer, same names remain distinct',async t=>{const {dir,store}=await fixture(t);await fs.mkdir(path.join(dir,'other'));const p=path.join(dir,'a.txt'),q=path.join(dir,'other','a.txt');await fs.writeFile(p,'A');await fs.writeFile(q,'B');await fs.symlink(p,path.join(dir,'alias.txt'));const first=await store.open(p),alias=await store.open(path.join(dir,'alias.txt')),second=await store.open(q);assert.deepEqual(alias,{id:first.id,existing:true});assert.notEqual(first.id,second.id);await store.close(first.id);assert.notEqual((await store.open(p)).id,first.id);});
test('external changes are protected until explicit overwrite',async t=>{const {dir,store}=await fixture(t),p=path.join(dir,'a.txt');await fs.writeFile(p,'A');const f=await store.open(p);await fs.writeFile(p,'external');await assert.rejects(store.save(f.id,'mine'),{code:'FILE_CHANGED'});assert.equal(await fs.readFile(p,'utf8'),'external');await store.save(f.id,'mine',{overwrite:true});assert.equal(await fs.readFile(p,'utf8'),'mine');await store.save(f.id,'second');});
test('invalid UTF-8 and removed original file fail without fake success',async t=>{const {dir,store}=await fixture(t),p=path.join(dir,'a.txt');await fs.writeFile(p,Buffer.from([0xff,0xfe]));await assert.rejects(store.open(p),/UTF-8/);await fs.writeFile(p,'A');const f=await store.open(p);await fs.rm(p);await assert.rejects(store.save(f.id,'edited'),{code:'ENOENT'});assert.deepEqual(await fs.readdir(dir),[]);});

test('concurrent saves are serialized, simultaneous opens reuse a single identity',async t=>{const {dir,store}=await fixture(t),p=path.join(dir,'a.txt');await fs.writeFile(p,'initial');const opened=await Promise.all([store.open(p),store.open(p)]);assert.equal(opened[0].id,opened[1].id);await Promise.all([store.save(opened[0].id,'first'),store.save(opened[0].id,'second')]);assert.equal(await fs.readFile(p,'utf8'),'second');await store.save(opened[0].id,'third');assert.equal(await fs.readFile(p,'utf8'),'third');});
